services:
    worker:
        image: 
            europe-west9-docker.pkg.dev/tuto-terraform-amine/voting-image/worker
        build:
            context: ./worker
            dockerfile: Dockerfile
        ports:
            - "80:80"
        depends_on:
            - redis
            - db
        environment:
            # BUILDPLATFORM: arm64
            # build-arg TARGETPLATFORM: linux/amd64
            # build-arg TARGETARCH: amd64
            REDIS_HOST: redis
            REDIS_PORT: 6379
            POSTGRES_HOST: db
            POSTGRES_DB: db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        networks:
            - back-tier

    redis:
        image: 
            "redis:alpine"
        ports:
            - "6379:6379"

        networks:
            - back-tier
    db:
        image: "postgres:alpine"
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes: 
        - db:/var/lib/postgresql/data
        networks:
            - back-tier
    result:
        image: 
            europe-west9-docker.pkg.dev/tuto-terraform-amine/voting-image/result
        build: ./result
        ports:
          - "4000:4000"
        depends_on:
            - db
        networks:
            - front-tier
            - back-tier
    
    vote:
        image: 
            europe-west9-docker.pkg.dev/tuto-terraform-amine/voting-image/vote
        build: ./vote  
        ports:
            - "5000:5000"
        depends_on:
            - redis
        networks:
            - front-tier
            - back-tier

    nginx:
        image: 
            europe-west9-docker.pkg.dev/tuto-terraform-amine/voting-image/nginx
        build: ./nginx
        ports:
          - "8001:8001"
        depends_on:
            - vote
        networks:
            - front-tier
    seed:
        image: 
            europe-west9-docker.pkg.dev/tuto-terraform-amine/voting-image/seed
        build: ./seed-data
        ports:
          - "9000:9000"
        depends_on:
            - nginx
        networks:
            - front-tier
            - back-tier
volumes:
  db:
    driver: local
networks:
    front-tier:
    back-tier:
