services:
    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile
        ports:
            - "80:80"
        depends_on:
            - redis
            - db
        environment:
            # BUILDPLATFORM: arm64
            # build-arg TARGETPLATFORM: linux/amd64
            # build-arg TARGETARCH: amd64
            REDIS_HOST: redis
            REDIS_PORT: 6379
            POSTGRES_HOST: db
            POSTGRES_DB: db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        networks:
            - back-tier

    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"

        networks:
            - back-tier
    db:
        image: "postgres:alpine"
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes: 
        - db:/var/lib/postgresql/data
        networks:
            - back-tier
    result:
        build: ./result
        ports:
          - "4000:4000"
        depends_on:
            - db
        networks:
            - front-tier
            - back-tier
    
    vote:
        build: ./vote  
        ports:
        - "5000:5000"
        depends_on:
        - redis
        networks:
        - front-tier
        - back-tier

    nginx:
        build: ./nginx
        ports:
          - "81:81"
        depends_on:
            - vote
        networks:
            - front-tier
    seed:
        build: ./seed-data
        depends_on:
            - nginx
        networks:
            - front-tier
volumes:
  db:
    driver: local
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
