apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: europe-west9-docker.pkg.dev/tuto-terraform-amine/voting-image/result
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  selector:
    app: result
  ports:
    - port: 4000
      targetPort: 4000
  type: LoadBalancer