apiVersion: v1
kind: Deployment
metadata:
  name: voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      labels:
        app: voting-app
    spec:
      containers:
      - name: vote
        image: europe-west9-docker.pkg.dev/calcium-firefly-448121-d3/voting-image/vote
        ports:
        - containerPort: 5000
